ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

# Home network
network={
    ssid="********" #put in home wi-fi SSID
    psk="********" #put in home wi-fi password
    priority=10
}

# School guest network (no password)
#Works for guest networks in general
network={
    ssid="********"
    key_mgmt=NONE
    priority=5
}
